//LOCALHOST 
### ALL
GET http://localhost:3000/contacts/
### KOH
GET http://localhost:3000/contacts/6480d0861951326bc9cb03c3
### JAQUELINE
GET http://localhost:3000/contacts/6480d16e1951326bc9cb03c5
### NAOYA
GET http://localhost:3000/contacts/6480d19e1951326bc9cb03c7
### MARIA
GET http://localhost:3000/contacts/6480d1d71951326bc9cb03c8
### ERIKA
GET http://localhost:3000/contacts/6480d2061951326bc9cb03ca
### MIKE
GET http://localhost:3000/contacts/6480d2541951326bc9cb03cc

//RENDER 
### ALL 
GET https://cse341-takamasa.onrender.com/contacts
### KOH 
GET https://cse341-takamasa.onrender.com/contacts/6480d0861951326bc9cb03c3
### JAQUELINE 
GET https://cse341-takamasa.onrender.com/contacts/6480d16e1951326bc9cb03c5
### NAOYA 
GET https://cse341-takamasa.onrender.com/contacts/6480d19e1951326bc9cb03c7
### MARIA 
GET https://cse341-takamasa.onrender.com/contacts/6480d1d71951326bc9cb03c8
### ERIKA 
GET https://cse341-takamasa.onrender.com/contacts/6480d2061951326bc9cb03ca
### MIKE 
GET https://cse341-takamasa.onrender.com/contacts/6480d2541951326bc9cb03cc